Batch SuperRes Example Processor
pytorch/examples pull request #519
Opened 2019-03-01 18:32 UTC by Bobrow

This contains a updated README.md file and a python file that repeatedly calls `python super_resolve.py` and all the required parameters and an extra requirements file for pip. It 1) Takes in a parameter from --image that tells it where the image you want to test the Super Resolution AI with
2) Scan the folder it is in to find any model_epochx.pth files and appends the to a list
3) Using Natsort(in the extrarequirements.txt file), it then sorts the list so that it goes from model_epoch_1.pth to the file with the biggest number
4) Calls `python super_resolve.py --input_image `(--image parameter)` --model `(using the default naming scheme for the model *.pth files)` --output_filename out`(the cycle the for loop is in + 1)`.png`
5) Prints how long it took, the output filename, the average time and the estimated time of finishing
6) Repeats 4 and 5 until all the model *.pth files are used

2022-03-09 19:02 UTC, msaroufim requested changes
I'd suggest you take a look at our existing examples to make your contribution look similar

2022-03-09 19:02 UTC, msaroufim commented on super_resolution/README.md
> +`python batchsuperres.py --image dataset/BSDS300/images/test/16077.jpg`
Where should people get this image?

2022-03-09 19:02 UTC, msaroufim commented on super_resolution/extrarequirements.txt
> +natsort
need a readme to tell people to install this

2022-03-09 19:02 UTC, msaroufim commented on super_resolution/batchsuperres.py
> +import subprocess, os, fnmatch, time, datetime, argparse
the format you're using is very different from any of our other examples, I'd suggest you take a look at them and see how your code can mimic it structurally

2022-03-09 19:02 UTC, closed without merging

2022-03-10 08:07 UTC, ProtoByter commented
I forgot about this PR lmfao, I just saw a bunch of emails from GitHub and I was like wait wtfI honestly can't remember why I did this :P