[WIP] Fix rpc param server example
pytorch/examples pull request #842
Opened 2020-11-17 00:55 UTC by rohan-varma

2020-12-14 09:27 UTC, Weigaa commented
Thank you for solving this problem, but does this solution mean that multiple workers train in series and cannot use multiple nodes to speed up the training process in parallel? e.g. I have 3 CPUs,1 PS, and 2  workers, and the workers' speed is v1 and v2, total training data size = n,now the training time = n/2v1 + n/2v2 but what we expect training time = n/2min(v1,v2)?

2020-12-14 12:58 UTC, Arunpoochelvan requested changes
Change line number 201 
    device = torch.device("cuda:0" if model.num_gpus > 0 
    device = torch.device("cuda:0" if model.num_gpus > 0
        and torch.cuda.is_available() else "cpu")

to 

    device = torch.device("cuda:0" if model.num_gpus > 0 
        and torch.cuda.is_available() else "cpu")

2021-01-28 06:54 UTC, rohan-varma commented
> Change line number 201
> device = torch.device("cuda:0" if model.num_gpus > 0
> device = torch.device("cuda:0" if model.num_gpus > 0
> and torch.cuda.is_available() else "cpu")
> 
> to
> 
> ```
> device = torch.device("cuda:0" if model.num_gpus > 0 
>     and torch.cuda.is_available() else "cpu")
> ```

Sorry for the late reply, but not sure if I follow this. Aren't these the same lines of code?

2022-03-17 16:11 UTC, msaroufim commented
Hi @rohan-varma the RPC example we have in this repo is from 1.4 do you think we should just go ahead and remove it?

2022-07-06 05:17 UTC, msaroufim commented
Closing since this is now stale

2022-07-06 05:17 UTC, closed without merging